name: Push to development server

on:
  push:
    branches: 
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xyz:latest
     
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Connect via SSH and deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            docker stop ${{ secrets.CNAME }} || true
            docker rm ${{ secrets.CNAME }} || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/xyz || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/xyz
            docker run --name ${{ secrets.CNAME }} \
              -p 8000:8000 \
              -d \
                -e ENVIRONMENT=development \
                -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
                -e MYSQL_PASS=${{ secrets.MYSQL_PASS }} \
                -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
                -e MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
                -e MYSQL_NAME=${{ secrets.MYSQL_NAME }} \
                -e MIDTRANS_SERVER_KEY=${{ secrets.MIDTRANS_SERVER_KEY }} \
                -e MIDTRANS_CLIENT_KEY=${{ secrets.MIDTRANS_CLIENT_KEY }} \
                -e SMTP_USER=${{ secrets.SMTP_USER }} \
                -e SMTP_PASS=${{ secrets.SMTP_PASS }} \
                -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
                -e SMTP_HOST=${{ secrets.SMTP_HOST }} \
                -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                -e SERVER_HOST=${{ secrets.SERVER_HOST }} \
                -e SERVER_PORT=${{ secrets.SERVER_PORT }} \
                ${{ secrets.DOCKERHUB_USERNAME }}/xyz
              ${{ secrets.DOCKERHUB_USERNAME }}/xyz